// <auto-generated />
using AngularAspCodeFirst.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AngularAspCodeFirst.Migrations
{
    [DbContext(typeof(FootballDbContext))]
    [Migration("20210325104428_InitialDbCreateAndSeedData")]
    partial class InitialDbCreateAndSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AngularAspCodeFirst.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Appearances")
                        .HasColumnType("int");

                    b.Property<int>("Goals")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("ShirtNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Appearances = 268,
                            Goals = 54,
                            Name = "Juan Mata",
                            Position = 3,
                            ShirtNo = 8
                        },
                        new
                        {
                            Id = 2,
                            Appearances = 130,
                            Goals = 28,
                            Name = "Paul Pogba",
                            Position = 2,
                            ShirtNo = 6
                        },
                        new
                        {
                            Id = 3,
                            Appearances = 335,
                            Goals = 0,
                            Name = "David de Gea",
                            Position = 0,
                            ShirtNo = 1
                        },
                        new
                        {
                            Id = 4,
                            Appearances = 200,
                            Goals = 2,
                            Name = "Phil Jones",
                            Position = 1,
                            ShirtNo = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
